### ISSUE TITLE
Allow queuing custom responses from function call

### ISSUE THREAD

**Issue by davidzhao** [livekit/agents#1054]
During a function call, sometimes it's desirable to let the user know that this is going to take awhile. While it is possible to prompt the LLM to return a text response while this is happening, it would offer more control to be able to do `agent.say("....")`.

Currently when that is done, the speech gets queued *after* the LLM's response. We'd want the ability to inject a response as the immediate thing that's communicated.

**Comment by Don-Chad** [comment]
It would be huge if we could even pre-buffer the audio for this message...  Thanks guys!

**Comment by theomonnom** [comment]
> It would be huge if we could even pre-buffer the audio for this message...  Thanks guys! 

Hey, what do you mean by pre-buffer, do you want to synthesize the agent speech ahead of time?

**Comment by Don-Chad** [comment]
@theomonnom hi Theo, yes exactly. Then we could get to very nice and low latencies with an initial prebuffered message, as we are streaming the full answer.

Hume for example is also offering this feature.

**Comment by longcw** [comment]
@davidzhao Where do you think the "quick response" before the function call done should come from:
prompt the LLM to say something after function_calls_collected or allow the function to early return a customized text before it done?

**Comment by davidzhao** [comment]
some folks are already prompting LLM to return the right text. I think others are choosing to use `agent.say` to queue up a custom placeholder response.

currently when trying the latter path, the speech doesn't get enqueued right away

**Comment by longcw** [comment]
> some folks are already prompting LLM to return the right text. I think others are choosing to use `agent.say` to queue up a custom placeholder response.
> 
> currently when trying the latter path, the speech doesn't get enqueued right away

I see. I can take a look if it's an issue of `agent.say` doesn't work as expected.

**Comment by longcw** [comment]
The current function call logic is like the following pseudo-code
```python
fncs = speech_handle.synthesis_handle.play().join()
chat_ctx = speech_handle.source.chat_ctx
nest = 0
while fncs and nest < max_nested:
  tools_messages = [fnc.exectue() for fnc in fncs]

  answer_llm_stream = llm.chat(chat_ctx.copy() + tools_messages)
  speech_handle.synthesis_handle = _synthesize_agent_speech(answer_llm_stream)

  fncs = speech_handle.synthesis_handle.play().join()
  nest += 1
```
So that the function call will block all later speech (also the one from `say`), and all the function calls share the same base chat_ctx from the `speech_handle.source`. Not sure if it's intended, the nested function call cannot be interrupted as the `interrupted = answer_synthesis.interrupted` is not used, though this might rarely happen https://github.com/livekit/agents/blob/main/livekit-agents/livekit/agents/pipeline/pipeline_agent.py#L820 

I have a proposal that we send the function calls in a fnc_queue and execute them in separate task. It records the nest index and the base `chat_ctx` for each function call task so it should have the same behavior like the current version. And any user interruption will cancel all the queued function calls.

 @theomonnom what do you think, is there any potential risk for implementing like that?
