### ISSUE TITLE
OpenAI realtime webRTC implementation

### ISSUE THREAD

**Issue by kikoncuo** [livekit/agents#1251]
A new way to connect directly the customer to the servers to reduce latency was released recently

https://platform.openai.com/docs/guides/realtime-webrtc

This is not an option due to how livekit works right?

**Comment by davidzhao** [comment]
this API is designed for clients to connect to directly. Since Agents is a backend orchestration framework, it wouldn't fit within it very well.

Re latency: Agents already benefit from LiveKit's global network, so it's already optimized quite a bit for that. I think the benefit this over the existing WebSocket API as it applies to Agents, would be limited.
