### ISSUE TITLE
OnDemand Agent

### ISSUE THREAD

**Issue by jasonison** [livekit/agents#214]
A use case we're exploring involves implementing a translator agent that would only be needed when participants are speaking different languages. It seems that an on-demand agent would be better suited than agents automatically joining the room since the translator agent wouldn't always be needed. We envision user interaction that allows for starting and stopping the agent as needed. Other than running "python my_agent.py simulate-job --room-name <my-room>", are there any other approaches for this or anything the team considering?

**Comment by Burry** [comment]
+1, for our use case this would be an easier integration with our Cloudflare Workers-based infrastructure. We previously were using Durable Objects to facilitate WebSocket connections, but the LiveKit Agent framework is much more robust than what we had. Being able to spin up and spin down agents at will would give us a lot more flexibility.

**Comment by theomonnom** [comment]
Can the PR above fits your usecase?

**Comment by Burry** [comment]
@theomonnom If I'm understanding livekit/protocol#683 correctly, then we'd be able to request an agent job run from any of the server SDKs? That would be quite helpful, but it's a bit limited without the ability to send custom parameters in that request. For example, our agent worker may be capable of running different named workflows, or we might want to have it respond to some custom event with a payload.

My prior comment was mainly motivated by the desire to stick with our serverless Cloudflare architecture rather than horizontally scaling containers or VMs running the Agent Framework. That would be much easier for us to scale in terms of cost and integration with our existing TypeScript codebase.

I might take a crack at implementing that myself if you believe it's possible, but it could be tricky if LiveKit Server is expecting these worker WebSockets to always stay connected. We could configure a WebHook to ping a Cloudflare Worker, which tells a Durable Object to establish a WebSocket connection to the LiveKit Server's agents endpoint. But it appears this would be incompatible with the Agents model. At that point, we might just have to set up the Durable Object to connect to the room directly since we're controlling the "agent"'s dispatch ourselves.

I'm curious if you have any thoughts on this.

**Comment by vanics** [comment]
+1 for this feature.

I also second Burry’s last comment as well.
I am looking to do something similar. 

Hopefully not bombing your post Burry but another feature that could be implemented to increase the flexibility of this is the ability to request an Agent to stop operating in a specific room.

in other words:
1 - You manually starts an agent using the server SDK and passing specific parameters to it.
When certain circumstances are met by your application, backend that concludes the use of a specific agent, you release that agent…
2 - You manually stops an agent from operating in a room using the server SDK

I am aware we can tweak the agent as we see fit but I’d imagine this would give greater flexibility to all and simplify certain implementations.

**Comment by keepingitneil** [comment]
@vanics it's a bit easier to tell the agent to stop than it telling it when to join. Using our server api sdk, you can send a data channel message to the agent and when conditions are met. Would that be useful for you?

I think the broader use case of more dynamic agent orchestration is fair. Something we can think about on our end.

@Burry 
I'll propose something as a workaround in the meantime.
- create a JT_ROOM (i.e. joins on room creation) agent that joins the room and acts as an orchestrator (namespace='orchestrator' or something like that)
- this agent does almost nothing, so you can fit many of them on your hosts without over-provisioning a bunch of translator agents
- the agent listens for conditions and decides when to add the translator agent to the room
- for initial conditions, the translator agent can either ask the orchestrator on startup (via datachannels) or they can be put into room metadata.

Would that work for you?

**Comment by davidzhao** [comment]
It's possible to control the dispatch workflow now, please refer to the docs here: https://docs.livekit.io/agents/build/dispatch/

**Comment by leemuljadi** [comment]
@Burry did you manage to implement livekit agent with cloudflare workers and durable objects? I'm looking for this solution for solving cold start for auto-scaling.
