### ISSUE TITLE
Can clients re-use token after disconnect?

### ISSUE THREAD

**Issue by quoctuanck99** [livekit/agents#256]
I recently used livekit for my application using agents example. And I had a problem:
### **What happended?**

I use Android application to connect to livekit with genereated token and wss url, everything is okay. Then I disconnect my client from livekit using room.disconnect(). I saw that my agents still running for this room. After that, I reconnect using the same token and I only see a black screen. 
In server side I saw this log:

> {"asctime": "2024-04-25 09:11:32,833", "level": "ERROR", "name": "livekit.agents", "message": "livekit_api::signal_client::signal_stream:178:livekit_api::signal_client::signal_stream - unhandled websocket message Err(Protocol(ResetWithoutClosingHandshake))", "job_id": "AJ_8oNxanmAa5c2", "pid": 133}
{"asctime": "2024-04-25 09:11:32,837", "level": "DEBUG", "name": "livekit", "message": "livekit::rtc_engine:377:livekit::rtc_engine - engine task closed"}
{"asctime": "2024-04-25 09:11:32,837", "level": "DEBUG", "name": "livekit", "message": "livekit::room:943:livekit::room - disconnected from room: UnknownReason"}

### **What I expected:**
I can re-use the token from client to re-connect to the room.
Please help, 
Thanks!

**Comment by keepingitneil** [comment]
Just cut some new stable releases (0.6) that handle this differently. But what's happening for you is:
- user joins room A with token
- livekit sees room creation and creates a job request for an agent on room A
- user leaves room A
- agent sees that there are no humans participants left, so the agent leaves the room
- user rejoins the same room before livekit has cleaned the room up (which is an asynchronous process)
- livekit doesn't re-add the agent because agents are added on new room creations

Going forward with the new release, agents will never leave the room on their own. Instead, the room will be deleted by the livekit backend when all human participants leave. But, using `departure_timeout` when creating the room, the room can be configured to stick around for some time even when there are no human participants left.

**Comment by Tryptophan** [comment]
@keepingitneil 

> Just cut some new stable releases (0.6) that handle this differently. But what's happening for you is:
> 
>     * user joins room A with token
> 
>     * livekit sees room creation and creates a job request for an agent on room A
> 
>     * user leaves room A
> 
>     * agent sees that there are no humans participants left, so the agent leaves the room
> 
>     * user rejoins the same room before livekit has cleaned the room up (which is an asynchronous process)
> 
>     * livekit doesn't re-add the agent because agents are added on new room creations
> 
> 
> Going forward with the new release, agents will never leave the room on their own. Instead, the room will be deleted by the livekit backend when all human participants leave. But, using `departure_timeout` when creating the room, the room can be configured to stick around for some time even when there are no human participants left.

in regards to your last bullet, is this already the case on livekit cloud/livekit agents 0.6.0? Or is this referring to a future release?
