### ISSUE TITLE
P2P options for LiveKit agents

### ISSUE THREAD

**Issue by nfiacco** [livekit/agents#353]
The LiveKit SFU architecture makes sense for conferencing and video broadcasting applications, but P2P makes more sense for agents that typically are engaging with a single client at a time. Would love to see a P2P connection option that is orchestrated by the LiveKit server!

**Comment by davidzhao** [comment]
hey @nfiacco, P2P definitely makes more sense in the one to one use case. though we not going to invest in it for now for a couple of reasons:
* P2P adds a lot of complexities, particularly because we rely on our SFU for a bunch of features WebRTC doesn't provide.
* P2P over long distances performs rather poorly, due to slow discovery of packet loss. Agents works with our Cloud mesh, where each connection is terminated at the closest edge server. This allows us to repair the streams quickly, and transporting the data over private backbones.

**Comment by nfiacco** [comment]
Totally fair— the SFU mesh system is really cool, definitely see the benefits of sticking with that infra

**Comment by Jeandcc** [comment]
I would like to re-open this discussion if possible. 

Imagine a product where the AI Agent relies on several video streams from the same user: Webcam + ScreenShare + Etc. (Video streams being processed by the AI through their latest frames). Add to that a scale of 5,000 users.

Thinking about that use case, let's run some math, with the assumption of videos with a bit-rate of 1mbps:

One hour duration = 1mb * 60 * 60 = 3600mb
3 Video Tracks = 3600 * 3 = 10800mb
Let's add scale (5000 users) = 10800mb * 5000 = 54 terabytes
With Livekit's Scale plan pricing = 54 TB  - 3 TB -> 51,000 GB * 0.1/GB -> 5.100 USD/mo

That's money that would not need to be spent if peer-to-peer for Livekit Agents was "a thing".

Orrrr, we could hope that [Livekit Agents Cloud](https://livekit.notion.site/LiveKit-Cloud-Agents-Beta-Docs-1c73c4901a42803eb2dffa077c3c719e) will place both the WebRTC servers and the Agent Servers on the same VPC/Network, therefore extinguishing the idea of the video stream having to properly egress the WebRTC Server Network to find the "Agent's network".

**Comment by davidzhao** [comment]
That's correct, with Agents cloud, we will not charge for ingest bandwidth
