### ISSUE TITLE
Ordering of user_speech_committed event and LLM invocation

### ISSUE THREAD

**Issue by Toubat** [livekit/agents#642]
Hey livekit team, I'm wondering why for the `VoiceAssistant`, the user message is not committed before synthesizing prompts & calling the LLM with that message?
https://github.com/livekit/agents/blob/7c3841b0c875cf2a34c5730c9e8fcf21a17ef6b6/livekit-agents/livekit/agents/voice_assistant/voice_assistant.py#L461-L476
Shouldn't calling LLM with the latest message mean that the user message has already been committed/determined?

Instead, the user speech committed event is triggered after the LLM finish the final response here. Is this designed by purpose?
https://github.com/livekit/agents/blob/7c3841b0c875cf2a34c5730c9e8fcf21a17ef6b6/livekit-agents/livekit/agents/voice_assistant/voice_assistant.py#L551-L552

**Comment by xianqiliu** [comment]
@Toubat Hey, do you have any answers or thoughts on your question? Because I saw you closed it. I also wonder if I can play the speech before the LLM finishes the final response, I guess if the agent can play the TTS audio while receiving the LLM stream, this can reduce the latency. 
Appreciate if you can share any ideas~~

**Comment by Toubat** [comment]
Hey @xianqiliu, thanks! I don't have a concrete idea on this actually. The codebase seems changed a lot after I created this issue. Let me dig into this a little bit more and I'll get back to you later!
