### ISSUE TITLE
When `allow_interruption=False`, we should ignore user's input

### ISSUE THREAD

**Issue by davidzhao** [livekit/agents#824]
When the agent is speaking with `allow_interruption=False`, we should not be processing any user input, instead of queuing up another response (only to play it out later).

That response will lack the proper context and the user would not be expecting that the agent heard it.

**Comment by martin-purplefish** [comment]
Related to this, with interruptions, the agent's state gets weird. If the agent is talking, and then the user speaks, the agent's state becomes listening rather than speaking.

To reproduce: subscribe to participant attributes changed, and have the agent say something with allow_interruptions=False, then say something while the agent is talking. You'll see the state becomes listening, even though the agent is still talking.

**Comment by lhylton** [comment]
I agree with ignoring a user's input while interruptions=False. Also applies to min_interrupt settings

**Comment by maik-parloa** [comment]
@davidzhao We are having the same issue with outbound calls and the initial message (to greet the user). We don't want the message to be interrupted by a user (e.g. by saying "hello, it's maik speaking") and just want to discard any user input until the welcome message has been spoken out to the user. Is there a way to delay listening to the user with the current state of the SDK?

**Comment by martin-purplefish** [comment]
@maik-parloa - one trick I use is in my before_llm_cb, if the agent is speaking, I return false.

**Comment by lhylton** [comment]
oh that's smart @martin-purplefish

**Comment by theomonnom** [comment]
This issue has been fixed in livekit-agents@0.10.2 in the [PR](https://github.com/livekit/agents/pull/869)
