### ISSUE TITLE
Integration with Whisper-compatible STT endpoints

### ISSUE THREAD

**Issue by davidzhao** [livekit/agents#981]
Inference providers like Groq are now supporting Whisper STT. we would like to ensure our OpenAI STT module could be used with Groq.

It'd be great to have `STT.with_groq(...)` constructors

**Comment by MSR2201** [comment]
I dont know about groq but i have made a whisper api in local and made it connect with the new plugin i made for whisper itself

**Comment by davidzhao** [comment]
nice, is that something you'd be open to sharing? :)

**Comment by MSR2201** [comment]
i have run whisper code its a pretty much a small api type and then I have made a code which can connect and get transcript from it just like deepgram api inference.  I have made it just yesterday because I am need for local models and i am also on the way to make a local TTS as well instead of the pricy ones online.
